---
common_user: vagrant

common_packages:
    - "build-essential"
    - "dos2unix"
    - "gcc"
    - "git"
    - "git-lfs"
    - "imagemagick"
    - "libnotify-bin"
    - "libpng-dev"
    - "pv"
    - "re2c"
    - "unzip"
    - "vim"
    - "whois"
    - "zsh"
    - "python3-pip"
    - "python3-dev"
    - "default-libmysqlclient-dev"
    - "net-tools"
    - "ffmpeg"
    - "yamllint"
    - "locales-all"

common_extra_bash_aliases:

common_apply_symlinks:

common_systemd_service_path: '/etc/systemd/system/'
